### ISSUE TITLE
Can you upload the checkpoint you use to generate the demo please?

### ISSUE THREAD

**Issue by CoolChameleon** [POZAlabs/ComMU-code#1]
Hello~
Thanks for your great work! I'm writing to ask if you can upload the checkpoint you use to generate the demo audio, for I'm having trouble reproducing your result. The results generated by my model have poor controllability and don't sound like real music, and I'm wondering if there's something wrong with my training.

**Comment by HyunLee103** [comment]
Thank you for your interest in our research! Disclosure of the pre-trained model ckpt will be discussed internally. But if you want, let me know the email and I will send you a ckpt. In addition, the quality of the generated mid file may be slightly different from the results on our demo page because it is influenced by DAW and virtual instruments that play the mid file.

**Comment by CoolChameleon** [comment]
Thanks a lot! Our email address is [pku_aimusic@outlook.com](mailto:pku_aimusic@outlook.com). Looking forward to it!

**Comment by blues-green** [comment]
Thanks for your great work! 
I would appreciate it if you could also send me a ckpt! 
My email address is vickyching0101@gmail.com.

> Thanks a lot! Our email address is [pku_aimusic@outlook.com](mailto:pku_aimusic@outlook.com). Looking forward to it!
