### ISSUE TITLE
what is duration_bins mean?

### ISSUE THREAD

**Issue by chh-han** [POZAlabs/ComMU-code#18]
I want to take a midi file and test it through the encoder. 

I've created a group with note items, and I'm wondering what 'duration_bins' means.
What do I need to create 'duration_bins'?

**Comment by hyeonch** [comment]
Apologies for the delay. In our encoding process, we don't map every MIDI tick to a token directly. Instead, we use sparse encoding, where each token represents a duration of 15 ticks in 4/4. While I mentioned a 4/4 time signature as an example, this approach is flexible and can be adapted for various time signatures.

To set up the 'duration_bins,' you can predefine a list of values like [15, 30, 45, ..., 1920]. These values are used as reference points for encoding note durations. When encoding MIDI data, you can parse the duration of a note and find the closest value in 'duration_bins' to represent that duration as a token.

For instance, if the duration of a note is 40, you would encode it as 45 because it's the closest value in the list, and the index of 45 in the list is 2. This index then serves as the encoded token for that note duration. (and finally add an predefined offset of the note duration category)
